package hu.elte.polozgai.movie.view;


import hu.elte.polozgai.movie.controller.ModositasController;
import hu.elte.polozgai.movie.model.Film;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author polozgai
 */
public class ModositasView extends javax.swing.JFrame {

    private ModositasController controller;
    private Film film;
    
    /**
     * {@link ModositasView} konstruálása.
     * @param controller {@link ModositasController}
     */
    public ModositasView(ModositasController controller) {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.controller=controller;
        this.film=this.controller.getFilm();
        eredetiAdatok();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mentesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cimField = new javax.swing.JTextField();
        rendezokField = new javax.swing.JTextField();
        foszereplokField = new javax.swing.JTextField();
        evField = new javax.swing.JTextField();
        hosszField = new javax.swing.JTextField();
        adathField = new javax.swing.JTextField();
        kepField = new javax.swing.JTextField();
        eredetiCheckBox = new javax.swing.JCheckBox();
        hanyszorField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Módosítás");

        mentesButton.setText("Mentés");
        mentesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mentesButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Cím");

        jLabel2.setText("Rendezõk");

        jLabel3.setText("Fõszereplõk");

        jLabel4.setText("Megjelenés");

        jLabel5.setText("Hossz");

        jLabel6.setText("Adathordozó típus");

        jLabel7.setText("Borítókép");

        jLabel9.setText("Hányszor adtuk kölcsön");

        eredetiCheckBox.setText("Eredeti");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(mentesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kepField)
                            .addComponent(adathField)
                            .addComponent(hosszField)
                            .addComponent(evField)
                            .addComponent(hanyszorField)
                            .addComponent(cimField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rendezokField)
                            .addComponent(foszereplokField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(eredetiCheckBox)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cimField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(rendezokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(foszereplokField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(evField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(hosszField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(adathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7))
                    .addComponent(kepField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(eredetiCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(hanyszorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(mentesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mentesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mentesButtonActionPerformed
        try{
            String cim=cimField.getText();
            String rendezo=rendezokField.getText();
            String foszereplo=foszereplokField.getText();
            String ev=evField.getText();
            String hossz=hosszField.getText();
            String adath=adathField.getText();
            boolean eredeti=eredetiCheckBox.isSelected();
            String hanyszor=hanyszorField.getText();
            String filename=kepField.getText();
            boolean kolcsonben=film.isVisszahozva();
            
            controller.editFilm(film.getId(),cim,rendezo,foszereplo,ev,hossz,adath,filename,eredeti,hanyszor,kolcsonben);
        }catch(Exception e){
            JOptionPane.showMessageDialog(new JFrame(), e.getMessage(), "Hiba", JOptionPane.ERROR_MESSAGE);
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_mentesButtonActionPerformed

    private void eredetiAdatok(){
        if(film!=null){
            cimField.setText(film.getCim());
            rendezokField.setText(film.getRendezok());
            foszereplokField.setText(film.getFoszereplok());
            evField.setText(Integer.toString(film.getMegjelenes()));
            hosszField.setText(Integer.toString(film.getHossz()));
            adathField.setText(film.getAdathordozoTipus());
            eredetiCheckBox.setSelected(film.isEredeti());
            hanyszorField.setText(Integer.toString(film.getHanyszor()));  
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adathField;
    private javax.swing.JTextField cimField;
    private javax.swing.JCheckBox eredetiCheckBox;
    private javax.swing.JTextField evField;
    private javax.swing.JTextField foszereplokField;
    private javax.swing.JTextField hanyszorField;
    private javax.swing.JTextField hosszField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField kepField;
    private javax.swing.JButton mentesButton;
    private javax.swing.JTextField rendezokField;
    // End of variables declaration//GEN-END:variables
}
